//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Instructions...")]
        public string Instructions {
            get {
                return ((string)(this["Instructions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This application shall be used to genearate a set of number sequences. ")]
        public string Instructions1 {
            get {
                return ((string)(this["Instructions1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          This will accept only positive numeric values (Minumum: 1 and Maximum" +
            ": 2,147,483,647) that will be used as the upper bound of the sequence.\r\n        " +
            "")]
        public string Instructions2 {
            get {
                return ((string)(this["Instructions2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          The sequences are Simple Sequence, Odd Numbers, Even Numbers and Fibo" +
            "nacci Sequences.\r\n        ")]
        public string Instructions3 {
            get {
                return ((string)(this["Instructions3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          There will be one more special sequence that will be similar to Simpl" +
            "e sequence. But the numbers that are divisible by 3 will be replaced by C, divis" +
            "ible by 3 will be replaced by E and divisible by 3 and 5 will be replaced by Z.\r" +
            "\n        ")]
        public string Instructions4 {
            get {
                return ((string)(this["Instructions4"]));
            }
        }
    }
}
