//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          This application shall be used to genearate a set of number sequences. <br/><br/>
          This will accept only positive numeric values that will be used as the upper bound of the sequence (Min: 1 and Max: 2,147,483,647). <br/><br/>
          The sequences are Simple Sequence, Odd Numbers, Even Numbers and Fibonacci Sequence. <br/><br/>
          There will be one more special sequence that will be similar to Simple sequence. But the numbers that are divisible by 3 will be replaced by C, divisible by 3 will be replaced by E and divisible by both 3 and 5 will be replaced by Z. <br/><br/>
        ")]
        public string Instructions {
            get {
                return ((string)(this["Instructions"]));
            }
        }
    }
}
